### ISSUE TITLE
When you set the weight on the outside the videoview inside doesn't fill up with the FrameLayout

### ISSUE THREAD

**Issue by xioayaohou** [WangZhiYao/Vitamio#2]
<FrameLayout
        android:id="@+id/video_layout"
        android:layout_width="match_parent"
        android:layout_weight="1"
        android:layout_height="0dp">

        <io.vov.vitamio.widget.VideoView
            android:id="@+id/video_videoView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <include layout="@layout/debris_video_control" />
    </FrameLayout>

   When you set the weight on the outside the videoview inside doesn't fill up with the FrameLayout

**Comment by WangZhiYao** [comment]
Forget it bro, you should use [Google ExoPlayer](https://github.com/google/ExoPlayer) instead of vitamio library, because vitamio is no longer maintained by official 4 years ago.
